image: Visual Studio 2017
platform: x64
shallow_clone: true
skip_tags: true
environment:
  GITHUB_TOKEN:
    secure: RD143wMIh7YPILU5pHittzdojuOUqJuuZYwjwmgqsGssSGeQf+yPeWmz5lpVI34f
install:
  - ps: Install-Product node Stable x64
  - npm ci
build: off
before_test:
  - git config --global user.name "John Doe"
  - git config --global user.email johndoe@example.com
test_script: npx --no-install mocha test.js --timeout 50000 --full-trace
